<?php

/**
 * @file
 * Provides Clerky module main functionality.
 */

module_load_include('inc', 'clerkly', 'queries');
module_load_include('inc', 'clerkly', 'validators');
module_load_include('inc', 'clerkly', 'helpers');


/**
 * Implements hook_init().
 */

function clerkly_init()
{

    if (arg(0) != 'admin') {
        $path = drupal_get_path('module', 'clerkly');
        drupal_add_css($path . '/assets/css/styles.css', array('group' => CSS_DEFAULT));
        drupal_add_library('system', 'jquery');
        drupal_add_js($path . '/assets/js/helpers.js', array('type' => 'file', 'group' => 'JS_DEFAULT'));
        drupal_add_js($path . '/assets/js/script.js', array('type' => 'file', 'group' => 'JS_DEFAULT'));

        ctools_include('modal');
        ctools_modal_add_js();

        drupal_add_js(array(
            'CToolsModal' => array(
                'modalSize' => array(
                    'type' => 'fixed',
                    'width' => 'auto',
                    'height' => 'auto',
                    'contentBottom' => 800),
            )
        ), 'setting');
    }
}

/**
 * Implements hook_menu().
 */

function clerkly_menu()
{

    $items = array();

    $items['admin/config/clerkly'] = array(
        'title' => 'Clerkly Settings',
        'description' => 'Here you can define Clerkly module global settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('clerkly_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'file' => 'clerkly.admin.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/clerkly/show_log'] = array(
        'title' => 'Text Correction Requests',
        'description' => 'Here you can see all text correction requests',
        'page callback' => 'correction_logs',
        'access arguments' => array('access administration pages'),
        'file' => 'clerkly.admin.inc',
    );

    $items['clerkly-popup/%node'] = array(
        'title' => 'Clerkly Typo Request',
        'access callback' => true,
        'page arguments' =>array(1),
        'page callback' => '_on_modal_show',
        'type' => MENU_CALLBACK,
    );

    return $items;

}

/**
 * Implements hook_form_field_ui_field_edit_form_alter().
 */

function clerkly_form_field_ui_field_edit_form_alter(&$form, &$form_state)
{
    $field_type = $form['#field']['type'];
    $instance = $form['#instance'];

    if ($field_type == 'text_with_summary' || $field_type == 'text_long' || $field_type == 'text') {

        $clerkly_settings = array();

        if (isset($instance['settings']['clerkly_settings'])) {
            $clerkly_settings = $instance['settings']['clerkly_settings'];
        }


        $form['instance']['settings'] += array(
            'clerkly_settings' => array(
                '#type' => 'fieldset',
                '#title' => t('Clerkly Settings'),
                '#collapsible' => TRUE,
                '#collapsed' => FALSE,
                '#weight' => 100,

                'clerkly_is_active' => array(
                    '#type' => 'select',
                    '#title' => t('Activate for current field:'),
                    '#description' => t('Activates/Deactivates Clerkly typo module for this field'),
                    '#default_value' => isset($clerkly_settings['clerkly_is_active'])
                                        ? $clerkly_settings['clerkly_is_active'] : true,
                    '#options' => array(
                        false => t('Deactivate'),
                        true => t('Activate'),
                    ),
                    '#element_validate' => array('element_validate_rich_text_enabled')
                ),
                'clerkly_email_typo' => array(
                    '#type' => 'textfield',
                    '#title' => t('Info Email'),
                    '#description' => t('Information Email that is used for sending of typo information'),
                    '#default_value' => isset($clerkly_settings['clerkly_email_typo'])
                                        ? $clerkly_settings['clerkly_email_typo'] : '',
                    '#element_validate' => array('element_validate_email')

                ),
                'clerkly_typo_length' => array(
                    '#type' => 'textfield',
                    '#title' => t('Typo Max Length'),
                    '#description' => t('Selected typo length'),
                    '#default_value' => isset($clerkly_settings['clerkly_typo_length'])
                                        ? $clerkly_settings['clerkly_typo_length'] : '',
                    '#element_validate' => array('element_validate_integer_positive', 'element_validate_max_length')

                ),
                'clerkly_popup_text' => array(
                    '#type' => 'textfield',
                    '#maxlength' => 255,
                    '#title' => t('Popup text'),
                    '#description' => t('Shows text for user in popup'),
                    '#default_value' => isset($clerkly_settings['clerkly_popup_text'])
                                        ? $clerkly_settings['clerkly_popup_text'] : ''

                )
            )

        );
    }
}

/**
 * Implements hook_preprocess_field().
 */

function clerkly_preprocess_field(&$variables)
{
    $field = &$variables['element'];

    if ($field['#field_type'] == 'text_with_summary' || $field['#field_type'] == 'text_long'
    || $field['#field_type'] == 'text') {

        $field_settings = _get_usable_settings($field);

        if (isset($field_settings['clerkly_is_active']) && !empty($field_settings['clerkly_is_active'])) {

            if (boolval($field_settings['clerkly_is_active']) === true
            && isset($field_settings['clerkly_max_chars'])) {

                $variables['classes_array'][] = 'clerkly-field';
                $variables['attributes_array'] = array(
                    'data-field' => $field['#field_name'],
                    'data-length' => $field_settings['clerkly_max_chars'],
                    'data-popup-text' => $field_settings['clerkly_popup_text']
                );

            }
        }
    }
}

/**
 * Implements hook_preprocess_node().
 */

function clerkly_preprocess_node(&$variables)
{
    $wrapper = entity_metadata_wrapper('node', 35);
    dprint_r($wrapper->type());
//    dprint_r($wrapper->getPropertyInfo());
    drupal_add_js(array('nid' => $variables['node']->nid), 'setting');
}

/**
 * Implements hook_form.
 */

function response_form($form, $form_state)
{

    $form = array();

    $form['#prefix'] = '<div id="clerkly-popup-window">';
    $form['#suffix'] = '</div>';

    $form['message_container'] = array(
        '#markup' => '<div id="clerkly-message"></div>'
    );

    $form['clerkly_info'] = array(
        '#markup' => '<p id="clerkly-popup-text"></p>'
    );

    $form['clerkly_selected_info'] = array(
        '#markup' => '<strong id="clerkly-selected-info"></strong>'
    );

    $form['clerkly_comment'] = array(
        '#title' => t('Write your comment here'),
        '#type' => 'textfield',
        '#attributes'=>array('id'=>'clerkly-modal-comment')
    );
    $form['field_type'] = array(
        '#type' => 'hidden',
        '#value' => '',
        '#attributes'=>array(
            'id'=>'clerkly-popup-field'
        )
    );

    $form['selected_text'] = array(
        '#type' => 'hidden',
        '#value' => '',
        '#attributes'=>array(
            'id'=>'clerkly-selection'
        )
    );


    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Send')
    );
    $form['#submit'][] = 'clerkly_response_form_submit';

    return $form;
}

/**
 * Implements hook_form_submit().
 */

function clerkly_response_form_submit($form, $form_state)
{

    $field_type = '';
    $comment = '';
    $commands = array();
    $selected_text = '';

    if (isset($form_state['input']['field_type']) && !empty($form_state['input']['field_type'])) {
        $field_type = $form_state['input']['field_type'];
    } else {
        $html = _get_markup_response('error');

        $commands[] = ajax_command_html('#clerkly-message', $html);
        watchdog('Error: ', 'Error occurred in clerkly module. field_type is empty');

        print ajax_render($commands);
        drupal_exit();
    }

    if (isset($form_state['input']['selected_text']) && !empty($form_state['input']['selected_text'])) {
        $selected_text = $form_state['input']['selected_text'];
    } else {
        $html = _get_markup_response('error');
        $commands[] = ajax_command_html('#clerkly-message', $html);
        watchdog('Error: ', 'Error occurred in clerkly module. String for correction was not selected');

        print ajax_render($commands);
        drupal_exit();
    }

    if (isset($form_state['input']['clerkly_comment'])) {
        $comment = $form_state['input']['clerkly_comment'];
    }

    if (!_send_form_reply($field_type, $selected_text, $comment, $form_state['build_info'])) {

        $html = _get_markup_response('error');
        $commands[] = ajax_command_html('#clerkly-message', $html);
        print ajax_render($commands);
        drupal_exit();
    }

    $html = _get_markup_response('success');
    $commands[] = ajax_command_html('#clerkly-message', $html);

    print ajax_render($commands);
    drupal_exit();
}

/**
 * Implements hook_theme()
 */

function clerkly_theme()
{

    $path = drupal_get_path('module', 'clerkly').'/templates';

    return array(
        'email_request' => array(
            'variables' => array(
                'node_type' => null,
                'node_url' => null,
                'field_name_ui' => null,
                'field_name' => null,
                'date_created' => null,
                'typo_text' => null,
                'comment_text' => null,
                'ip' => null,
                'uid' => null
            ),
            'template' => 'custom_email_template',
            'path' => $path
        )

    );
}

/**
 * Implements hook_mail()
 */

function clerkly_mail($key, &$message, $params)
{

    if ($key == 'clerkly_mail') {
        try {
            $headers = array(
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
                'Content-Transfer-Encoding' => '8bit',
                'X-Mailer' => 'Drupal',
            );

            if (isset($params['ip']) && !empty($params['ip'])) {
                $params['ip'] = long2ip($params['ip']);
            }

            if (isset($params['uid']) && !empty($params['uid'])) {

                $user_info = user_load($params['uid']);

                if (is_object($user_info) && !empty($user_info->name)) {
                    $params['uid'] = $user_info->name;
                }

            }

            $body = theme('email_request', $params);
            $message['subject'] = t('Request for text correction');
            $message['body'][] = $body;
            $message['headers'] = array_replace($message['headers'], $headers);
        } catch(Exception $e) {
            watchdog('mail', $e->getMessage());
        }
    }

}




